# GHC 9.6.4
# Update `defaultGHCVersion` in `./flake.nix` when updating to resolver with different GHC version.
resolver: lts-23.17

packages:
- .

extra-deps:
- levenshtein-0.2.1.0

nix:
  packages: [zlib]
